# Generated by Django 4.2.30 on 2026-04-13 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='image_url',
            field=models.URLField(blank=True, help_text='Вставьте ссылку на картинку (будет использоваться вместо загруженного файла)', max_length=500, null=True, verbose_name='Ссылка на изображение'),
        ),
    ]
