# Generated by Django 4.2.30 on 2026-04-21 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_comic_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='preview_pages',
            field=models.JSONField(blank=True, default=list, help_text='Список URL изображений страниц в формате JSON, например ["https://...", "..."]', verbose_name='Страницы отрывка'),
        ),
    ]
